source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.1"
use_frameworks!

target "Obfuscation" do
	pod 'Alamofire', '~> 4.0'
	pod 'Obfuscator', :git => 'https://github.com/pjebs/Obfuscator-iOS.git', :branch => 'master'
end
